---
- name: Install HAProxy
  yum:
    name: haproxy
    state: present
  notify: start haproxy
- name: Render and copy haproxy.conf
  template:
    src: templates/haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart haproxy
