- name: restart nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
- name: restart haproxy
  systemd:
    name: haproxy
    enabled: yes
    state: restarted
- name: restart dhcpd
  systemd:
    name: dhcpd
    enabled: yes
    state: restarted