---
- hosts: centos_servers
  vars_files: 
    - "environments/main.yaml"
  become:
    true
  become_method:
    su
  become_user:
    root
  remote_user:
    ansible
  roles:
   - tftp
   - dhcpd
   - haproxy
   - nginx